// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:reverse_singing_challenge/shared/models/challenge_model.dart';
import 'package:reverse_singing_challenge/shared/models/player_model.dart';
import 'package:reverse_singing_challenge/shared/models/session_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ChallengeModelAdapter());
    registerAdapter(PlayerModelAdapter());
    registerAdapter(SessionModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ChallengeModelAdapter());
    registerAdapter(PlayerModelAdapter());
    registerAdapter(SessionModelAdapter());
  }
}
